service:
  name: ringcentral-chatbot-js
provider:
  stage: ${opt:stage, 'dev'}
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  memorySize: 128
  environment: ${file(./.env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
package:
  exclude:
    - ./**
    - '!dist/**'
    - '!node_modules/**'
  excludeDevDependencies: true
functions:
  app:
    handler: dist/index.handler
    timeout: 300 # 5 miutes
  proxy:
    handler: dist/index.proxy
    events:
      - http: 'ANY {proxy+}'
